comment: false

coverage:
  status:
    project: linreg.package.Rproj
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
